// AUTO-GENERATED — run `node scripts/import_speakers_updated.js` to regenerate.
import { Speaker } from "@/types";

export const speakers: Speaker[] = [
  // ========================
  // GOVERNOR
  // ========================
  {
    id: "sp-h-e-rt-hon-francis-nwifuru",
    name: "H.E Rt. Hon. Francis Nwifuru",
    email: "",
    position: "object-top",
    role: "Governor of Ebonyi State",
    image: "/speakers/nwifuru.jpeg",
    bio: "The Governor of Ebonyi State",
    category: "All",
    socials: {},
  },

  // ========================
  // VICE CHANCELLORS
  // ========================
  {
    id: "sp-prof-chigozie-jesse-uneke",
    name: "Prof. Chigozie Jesse Uneke",
    email: "",
    position: "object-top",
    role: "Vice Chancellor, David Umahi Federal University of Health Sciences (DUFUHS)",
    image: "/speakers/prof-chigz.jpeg",
    bio: "Vice Chancellor of David Umahi Federal University of Health Sciences (DUFUHS)",
    category: "All",
    socials: {},
  },
  {
    id: "sp-professor-daniel-nwachukwu",
    name: "Professor Daniel Nwachukwu",
    email: "",
    position: "object-top",
    role: "Vice Chancellor, Alex Ekwueme Federal University Ndufu-Alike (AE-FUNAI)",
    image: "/speakers/prof-dan-nwachukwu.jpeg",
    bio: "The Vice-Chancellor of Alex Ekwueme Federal University Ndufu-Alike (AE-FUNAI)",
    category: "All",
    socials: {},
  },
  {
    id: "sp-prof-micheal-ugota-awoke",
    name: "Prof. Micheal Ugota Awoke",
    email: "",
    role: "Vice Chancellor, Ebonyi State University (EBSU)",
    image: "/speakers/prof-michael.jpeg",
    bio: "The Vice Chancellor (VC) of Ebonyi State University (EBSU)",
    category: "All",
    socials: {},
  },
  // ========================
  // CEO (BRILL)
  // ========================
  {
    id: "sp-adum-obinna",
    name: "Adum Obinna Abraham",
    email: "",
    role: "Founder, Dtcsi Academy • Convener, Technova",
    image: "/speakers/brill.jpeg",
    bio: "Founder Dtcsi Academy, Convener Technova",
    category: "All",
    socials: {},
  },

  // ========================
  // FOUNDERS / CEOs
  // ========================
  {
    id: "sp-toochukwu-okoro",
    name: "Toochukwu Okoro",
    email: "tc@blocverse.com",
    position: "object-top",
    role: "Co-Founder & CEO, Blocverse • Co-Founder, UseAzza",
    image: "/speakers/Toochukwu Okoro.jpeg",
    bio: "Co founder and CEO blocverse & UseAzza",
    category: "All",
    socials: {},
  },
  {
    id: "sp-awosika-israel-ayodeji",
    name: "Awosika Israel Ayodeji",
    email: "ayodeji@web3bridge.com",
    role: "Founder, Web3Bridge",
    image: "/speakers/awosika.jpeg",
    bio: `Awosika Israel Ayodeji is a passionate entrepreneur and the founder of Web3Bridge...`,
    category: "All",
    socials: {},
  },
  {
    id: "sp-samuel-oladokun-olaoyenikan-xeus-the-great",
    name: "Samuel Oladokun Olaoyenikan (Xeus The Great)",
    email: "definirvana@gmail.com",
    role: "Founder, Nirvana Academy • Convener, BlockFest Africa",
    position: "object-center",
    image: "/speakers/samuel-ola.jpeg",
    bio: "Founder, Nirvana Academy. Convener, BlockFest Africa.",
    category: "All",
    socials: {},
  },
  {
    id: "sp-momoh-kingsley",
    name: "Momoh Kingsley",
    email: "momohkingsley17@gmail.com",
    role: "Founder, NFT NG • Blockchain Evangelist & Key Opinion Leader",
    image: "/speakers/momoh-kingsley.jpeg",
    bio: "Founder of NFT NG and blockchain evangelist.",
    category: "All",
    socials: {},
  },
  {
    id: "sp-ekoyo-chijioke-prosper-mr-spella",
    name: "Ekoyo Chijioke Prosper (Mr. Spella)",
    email: "Cjprochat5@gmail.com",
    role: "Founder, Spella ICT Hub • AI/ML Engineer & Community Architect",
    image: "/speakers/ekoyo-chijioke.jpg",
    bio: "AI/ML Engineer and Founder of Spella ICT Hub.",
    category: "All",
    socials: {},
  },
  {
    id: "sp-okwosi-obed-chichetaram",
    name: "Okwosi Obed Chichetaram",
    email: "Trustnova@gmail.com",
    role: "Founder, Trustnova • Tech & Innovation Communicator",
    image: "/speakers/trust-nova.jpeg",
    bio: "Founder, Trustnova | Blogging, real estate, tech & innovation.",
    category: "All",
    socials: {},
  },

  // ========================
  // ECOSYSTEM LEADERS
  // ========================
  {
    id: "sp-chidubem-emelumadu",
    name: "Chidubem Emelumadu",
    email: "chidubem.emelumadu@lisk.com",
    role: "Ecosystem Lead for Africa, Lisk",
    image: "/speakers/chidubem-emelumadu.jpg",
    bio: "Ecosystem Lead for Africa at Lisk.",
    category: "All",
    socials: {},
  },
  {
    id: "sp-kevin-chibuoyim-okoye-ezemmuo-blockchain",
    name: "Kevin Chibuoyim Okoye (Ezemmuo Blockchain)",
    email: "kevinchibuoyim@gmail.com",
    role: "Lead, ETH Enugu & GIDA • Ecosystem Growth & Education Advocate",
    position: "object-top",
    image: "/speakers/kevin.jpeg",
    bio: "Lead of ETH Enugu & GIDA - an EduTech Academy.",
    category: "All",
    socials: {},
  },
  {
    id: "sp-sir-khaycee",
    name: "Sir Khaycee",
    email: "Khaycee99@gmail.com",
    role: "Founder, The Rebirth Odyssey • Web3 Growth Strategist & Community Builder",
    image: "/speakers/sir-khaycee.jpg",
    bio: "Web3 growth strategist and community builder.",
    category: "All",
    socials: {},
  },

  // ========================
  // OTHERS
  // ========================
  {
    id: "sp-kyrian-alex",
    name: "Kyrian Alex",
    email: "Alexanazodo@gmail.com",
    position: "object-top",
    role: "Research Analyst, Cointelegraph Research",
    image: "/speakers/Kyrian.jpeg",
    bio: "Research Analyst at Cointelegraph Research.",
    category: "All",
    socials: {},
  },
  {
    id: "sp-bms",
    name: "BMS",
    email: "Bloomstar042@gmail.com",
    role: "DeFi Analyst",
    image: "/speakers/bms.jpeg",
    bio: "Defi Analyst",
    category: "All",
    socials: {},
  },
  {
    id: "sp-headboy",
    name: "HEADBOY",
    email: "headboy280@gmail.com",
    role: "Crypto Educator & Defi expert",
    image: "/speakers/headboy.png",
    bio: "Crypto Educator & Defi expert",
    category: "All",
    socials: {},
  },
  {
    id: "sp-osita-kelvin",
    name: "Osita Kelvin",
    email: "ositakelvin0@gmail.com",
    role: "Founder & CEO, NIKHIL Edutech • Financial Market Trader",
    image: "/speakers/osita-kelvin.jpeg",
    bio: "Professional Financial market trader and founder of NIKHIL Edutech",
    category: "All",
    socials: {},
  },
  {
    id: "sp-john-nwenyi",
    name: "John Nwenyi",
    position: "object-center",
    email: "Udokajohn6@gmail.com",
    role: "Legal practitioner and Managing Partner, Apus Consult & Legal Practitioners • Corporate & Cyberlaw Specialist",
    image: "/speakers/john-nwenyi.jpg",
    bio: "Legal practitioner and Managing Partner.",
    category: "All",
    socials: {},
  },
  {
    id: "sp-ugwu-somto",
    name: "Ugwu Somto",
    email: "ugwujude42@gmail.com",
    position: "object-bottom",
    role: "Software Engineer • Co-Founder, Digitpay Finance",
    image: "/speakers/ugwu-somto.jpeg",
    bio: "Software Engineer and Co-founder of Digitpay Finance",
    category: "All",
    socials: {},
  },
  {
    id: "sp-sarah-idahosa",
    name: "Sarah Idahosa",
    email: "sarahidahosa001@gmail.com",
    position: "object-top",
    role: "Web3 Community Builder • DeFi Researcher & Education Advocate",
    image: "/speakers/sarah-idahosa.png",
    bio: "Web3 community development specialist.",
    category: "All",
    socials: {},
  },
  {
    id: "sp-thegreatola",
    name: "Thegreatola",
    email: "",
    role: "Founder, Elixr_Hd • Web3 Creator",
    image: "/speakers/theGreatOla.jpeg",
    bio: "Founder Elixr_Hd, Web3 Creator",
    category: "All",
    socials: {},
  },
  {
    id: "sp-joshua-nwankwo",
    name: "Joshua Nwankwo",
    email: "u.joshuanwankwo@gmail.com",
    role: "Founder, Letsdap",
    image: "/speakers/joshua-nwankwo.jpeg",
    bio: "Founder of Letsdap",
    category: "All",
    socials: {},
  },
  {
    id: "sp-ifeanyi",
    name: "Ifeanyi",
    email: "ifeanyi.oyom@gmail.com",
    role: "Chief Janito, InsideTheHive",
    image: "/speakers/Ifeanyi Oyom.jpeg",
    bio: "Chief Janito, InsideTheHive",
    category: "All",
    socials: {},
  },
  {
    id: "sp-kokeb-solomon",
    name: "Kokeb Solomon",
    email: "",
    role: "Cofounder, Web3 clubs",
    image: "/speakers/kokeb-solomon.jpeg",
    bio: "Cofounder, Web3 clubs",
    category: "All",
    socials: {},
  },
];
